[package]

name = "secret-storage"
version = "0.1.0"
edition = "2021"


[dependencies]

serde = { version = "1.0.130", features = ["derive"], optional = true }
bcs = { version = "0.1.6", optional = true }
fastcrypto = { version = "0.1", optional = true }
anyhow = "1.0.40"
iota-types = { git = "https://github.com/MystenLabs/sui.git", package = "sui-types", optional = true }
shared-crypto = { git = "https://github.com/MystenLabs/sui.git", package = "shared-crypto", optional = true }

[features]

transaction_helpers = [
  "serde",
  "iota-types",
  "shared-crypto",
  "bcs",
  "fastcrypto",
]
