[package]

name = "secret-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = { version = "0.1.80" }
thiserror = "1.0.63"

[features]
default = ["send-sync-storage"]
send-sync-storage = []
