name: Audit

on:
  push:
    branches:
      - main
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '.github/workflows/audit.yml'
      - '.cargo/audit.toml'
  pull_request:
    branches:
      - main
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '.github/workflows/audit.yml'
      - '.cargo/audit.toml'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
